export const PageTitle = {
  Home: 'Dashboard',
  UserProfile: 'User Profile',
  UserProfileCreate: 'Create UserProfile',
  UserProfileDetails: 'UserProfile Details',
  SecurityPrivilege: 'Security Privilege',
  SecurityRole: 'Security Role',
  SecurityGroup: 'Security Group',
  SecurityGroupCreate: 'Create Security Group',
  SecurityGroupUserCreate: 'Create Security Group User ',
  RolePrivilegeCreate: 'Create Security Role Privilege',
  RolePrivilege: 'Security Role Privilege',
  RoleGroup: 'Security Role Group',
  RoleGroupCreate: 'Create Security Role Group',
  CreateSecurityRole: 'Create Security Role',
  SecurityGroupDetails: 'Security Group Details',
  RoleDetails: 'Security Role Details',
  SecurityGroupRoleDetails: 'Security Group Role Details',
  SecurityGroupUserDetails: 'Security Group User Details',
  SecurityRolePrivilegeDetails: 'Security Role Privilege Details',
  PrivilegeCreate: 'Create Security Privilege',
  SecurityPrivilegeDetails: 'Security Privilege Details',
  UserGroup: 'Security User Group',
  ZipCode: 'Zip Code',
  State: 'State',
  Enterprice: 'Enterprice',
  UserHealthParam: 'User Health Param',
  UserHealthParamCreate: 'Create UserHealthParam',
  UserHealthParamDetails: 'UserHealthParam Details',
  UserPreference: 'User Preference',
  UserPreferenceCreate: 'Create UserPreference',
  UserPreferenceDetails: 'UserPreference Deatails',
  LabTestMaster: 'Lab Test Master',
  LabTestMasterCreate: 'Create LabTestMaster',
  Country: 'Country',
  TestPrice: 'Test Price',
  TestPriceCreate: 'Create Test Price',
  TestPriceDetails: 'Test Price Details',
  TestParameterMaster: 'Test Parameter Master',
  TestParameterMasterCreate: 'Create Test Parameter Master',
  TestParameterMasterDetails: 'Test Parameter Master Details',
  TestPackage: 'Test Package',
  TestPackageCreate: 'Create Test Package',
  TestPackageDetails: 'Test Package Details',
  TestPackagePrice: 'Test Package Price',
  TestPackagePriceCreate: 'Create Test Package Price',
  TestPackagePriceDetails: 'Test Package Price Details',
  TestPackageList: 'Test Package List',
  TestPackageListCreate: 'Create Test Package List',
  TestPackageListDetails: 'Test Package List Details',
  TestMaster: 'Test Master',
  TestMasterDetails: 'Test Master Details',
  CreateTestMaster: 'Create Test Master',
  BloodGroup: 'Blood Group',
  CreateBloodGroup: 'Create Blood Group',
  BloodGroupDetails: 'Blood Group Details',
  BusinessEntity: 'Business Entity',
};
