
export const ApiQueryKey = {
  accessGroups: 'accessGroups',
  accesssecurityRolePrivilege: 'accesssecurityRolePrivilege',
  accessSecurityGroupRole: 'accessSecurityGroupRole',
  accessRoles: 'accessRoles',
  accessPrivilege: 'accessPrivilege',
  accessSecurityGroupUser: 'accessSecurityGroupUser',
  users: 'users',
  state: 'state',
  zipcode: 'zipcode',
  userHealthParam: 'userHealthParam',
  labTestMaster: 'labTestMaster',
  userPreference: 'userPreference',
  enterprise: 'enterprise',
  userCreate: 'userCreate',
  country:'country',
  GroupUserCreate: 'GroupUserCreate',
  SecurityRolePrivilegeUserCreate: 'SecurityRolePrivilegeUserCreate',
  SecurityGroupRoleCreate: 'SecurityGroupRoleCreate',
  PrivilegeUserCreate: 'PrivilegeUserCreate',
  roleCreate: 'roleCreate',
  SecurityGroupUserCreate: 'SecurityGroupUserCreate',
  userPreferenceCreate: 'userPreferenceCreate',
  labTestMasterCreate: 'labTestMasterCreate',
  testPrice: 'testPrice',
  testPriceCreate: 'testPriceCreate',
  testParameterMaster: 'testParameterMaster',
  testPackage: 'testPackage',
  testPackageDetail: 'testPackageDetail',
  testPackagePriceCreate: 'testPackagePriceCreate',
  testPackageCreate: 'testPackageCreate',
  testParametermaster: 'testParametermaster',
  userHealthParamCreate: 'userHealthParamCreate',
  testPackagePrice: 'testPackagePrice',
  testPackageListCreate: 'testPackageListCreate',
  testPackageList: 'testPackageList',
  testMasterCreate: 'testMasterCreate',
  testMaster: 'testMaster',
  bloodGroupCreate: 'bloodGroupCreate',
  bloodGroup: 'bloodGroup',
  businessEntity: 'businessEntity',
};
